"""Add fundraising fields to Event

Revision ID: 0f78c499d157
Revises: 1c57b14aa51d
Create Date: 2023-11-07 01:25:42.303970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f78c499d157'
down_revision = '1c57b14aa51d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_fundraiser', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('funds_raised', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('funds_goal', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('funds_goal')
        batch_op.drop_column('funds_raised')
        batch_op.drop_column('is_fundraiser')

    # ### end Alembic commands ###
