"""Add fundraising fields to Event

Revision ID: 8aa52e10be2e
Revises: 0f78c499d157
Create Date: 2023-11-07 01:29:37.971744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa52e10be2e'
down_revision = '0f78c499d157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               nullable=True)

    # ### end Alembic commands ###
